# Generated by Django 2.1.1 on 2018-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('audio', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
            ],
        ),
    ]
